# https://taskfile.dev

version: '3'

vars:
  PI_HOST: 192.168.1.31
  K3D_CLUSTER: k3s-local

tasks:
  # ============================================================================
  # Development
  # ============================================================================
  dev:
    desc: Start local development environment
    dir: docker
    cmds:
      - docker compose up -d

  down:
    desc: Stop local development environment
    dir: docker
    cmds:
      - docker compose down

  logs:
    desc: View local development logs
    dir: docker
    cmds:
      - docker compose logs -f

  # ============================================================================
  # Build
  # ============================================================================
  build:
    desc: Build all applications
    cmds:
      - pnpm build

  build:docker:
    desc: Build Docker images for all apps
    cmds:
      - |
        for app in apps/*/; do
          if [ -f "$app/Dockerfile" ]; then
            app_name=$(basename $app)
            echo "Building $app_name..."
            docker build -t $app_name:local $app
          fi
        done

  # ============================================================================
  # K3d (Local Kubernetes)
  # ============================================================================
  k3d:create:
    desc: Create local K3s cluster with K3d
    cmds:
      - k3d cluster create --config docker/k3d-config.yaml
      - echo "Local cluster '{{.K3D_CLUSTER}}' created"
      - echo "Kubeconfig automatically updated"

  k3d:delete:
    desc: Delete local K3s cluster
    cmds:
      - k3d cluster delete {{.K3D_CLUSTER}}
      - echo "Local cluster '{{.K3D_CLUSTER}}' deleted"

  k3d:start:
    desc: Start local K3s cluster
    cmds:
      - k3d cluster start {{.K3D_CLUSTER}}

  k3d:stop:
    desc: Stop local K3s cluster
    cmds:
      - k3d cluster stop {{.K3D_CLUSTER}}

  k3d:list:
    desc: List K3d clusters
    cmds:
      - k3d cluster list

  # ============================================================================
  # Local Deployment
  # ============================================================================
  local:deploy:
    desc: Deploy full observability stack to local cluster
    cmds:
      - task: local:deploy:traefik
      - task: local:deploy:prometheus
      - task: local:deploy:loki
      - task: local:deploy:promtail
      - task: local:deploy:grafana
      - 'echo "Stack deployed! Run task local:test to validate"'

  local:deploy:traefik:
    desc: Deploy Traefik to local cluster
    cmds:
      - helm repo add traefik https://traefik.github.io/charts || true
      - helm repo update
      - |
        helm upgrade --install traefik traefik/traefik \
          -n kube-system \
          -f infrastructure/helm-values/local/traefik.yaml \
          --wait

  local:deploy:prometheus:
    desc: Deploy Prometheus to local cluster
    cmds:
      - helm repo add prometheus-community https://prometheus-community.github.io/helm-charts || true
      - helm repo update
      - kubectl create namespace monitoring --dry-run=client -o yaml | kubectl apply -f -
      - |
        helm upgrade --install prometheus prometheus-community/prometheus \
          -n monitoring \
          -f infrastructure/helm-values/local/prometheus.yaml \
          --wait

  local:deploy:loki:
    desc: Deploy Loki to local cluster
    cmds:
      - helm repo add grafana https://grafana.github.io/helm-charts || true
      - helm repo update
      - kubectl create namespace monitoring --dry-run=client -o yaml | kubectl apply -f -
      - |
        helm upgrade --install loki grafana/loki \
          -n monitoring \
          -f infrastructure/helm-values/local/loki.yaml \
          --wait

  local:deploy:promtail:
    desc: Deploy Promtail to local cluster
    cmds:
      - helm repo add grafana https://grafana.github.io/helm-charts || true
      - helm repo update
      - kubectl create namespace monitoring --dry-run=client -o yaml | kubectl apply -f -
      - |
        helm upgrade --install promtail grafana/promtail \
          -n monitoring \
          -f infrastructure/helm-values/local/promtail.yaml \
          --wait

  local:deploy:grafana:
    desc: Deploy Grafana to local cluster
    cmds:
      - helm repo add grafana https://grafana.github.io/helm-charts || true
      - helm repo update
      - kubectl create namespace monitoring --dry-run=client -o yaml | kubectl apply -f -
      - |
        helm upgrade --install grafana grafana/grafana \
          -n monitoring \
          -f infrastructure/helm-values/local/grafana.yaml \
          --wait

  local:test:
    desc: Validate local cluster deployment
    cmds:
      - ./scripts/validate-cluster.sh

  local:reset:
    desc: Delete and recreate local cluster
    cmds:
      - task: k3d:delete
      - task: k3d:create
      - echo "Cluster reset complete"

  # ============================================================================
  # Raspberry Pi Setup
  # ============================================================================
  pi:setup:
    desc: Initial Raspberry Pi setup via Ansible
    dir: ansible
    cmds:
      - ansible-playbook -i inventory/hosts.yml playbooks/setup.yml

  pi:ping:
    desc: Test connection to Raspberry Pi
    dir: ansible
    cmds:
      - ansible -i inventory/hosts.yml all -m ping

  pi:ssh:
    desc: SSH into Raspberry Pi
    cmds:
      - ssh pi@{{.PI_HOST}}

  pi:reboot:
    desc: Reboot Raspberry Pi via Ansible
    dir: ansible
    cmds:
      - ansible-playbook -i inventory/hosts.yml playbooks/reboot.yml

  # ============================================================================
  # K3s
  # ============================================================================
  k3s:install:
    desc: Install K3s on Raspberry Pi
    dir: ansible
    cmds:
      - ansible-playbook -i inventory/hosts.yml playbooks/k3s-install.yml

  k3s:uninstall:
    desc: Uninstall K3s from Raspberry Pi
    cmds:
      - ssh pi@{{.PI_HOST}} '/usr/local/bin/k3s-uninstall.sh'

  k3s:kubeconfig:
    desc: Fetch kubeconfig from Raspberry Pi to ~/.kube/config-pi
    cmds:
      - mkdir -p ~/.kube
      - |
        ssh pi@{{.PI_HOST}} 'sudo cat /etc/rancher/k3s/k3s.yaml' | \
        sed "s/127.0.0.1/{{.PI_HOST}}/g" | \
        sed "s/default/pi-cluster/g" > ~/.kube/config-pi
      - chmod 600 ~/.kube/config-pi
      - echo "Kubeconfig saved to ~/.kube/config-pi"
      - 'echo "Use: export KUBECONFIG=~/.kube/config-pi"'
      - 'echo "Or use: KUBECONFIG=~/.kube/config-pi kubectl get nodes"'

  # ============================================================================
  # ArgoCD
  # ============================================================================
  secrets:create:
    desc: Create shared secrets from .env file
    dotenv: ['.env']
    cmds:
      - kubectl create namespace monitoring --dry-run=client -o yaml | kubectl apply -f -
      - |
        kubectl create secret generic shared-credentials \
          --from-literal=admin-user=admin \
          --from-literal=admin-password=${SERVICES_PASSWORD} \
          -n monitoring --dry-run=client -o yaml | kubectl apply -f -
      - echo "Shared credentials secret created in monitoring namespace"

  secrets:create-openclaw:
    desc: Create OpenClaw secrets from .env file
    dotenv: ['.env']
    cmds:
      - kubectl create namespace openclaw --dry-run=client -o yaml | kubectl apply -f -
      - |
        kubectl create secret generic openclaw-secrets \
          --from-literal=groq-api-key=${GROQ_API_KEY} \
          --from-literal=telegram-bot-token=${TELEGRAM_BOT_TOKEN} \
          -n openclaw --dry-run=client -o yaml | kubectl apply -f -
      - echo "OpenClaw secrets created in openclaw namespace"

  argocd:install:
    desc: Install ArgoCD on the cluster
    cmds:
      - kubectl create namespace argocd --dry-run=client -o yaml | kubectl apply -f -
      - kubectl apply -n argocd --server-side -f https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml
      - echo "Waiting for ArgoCD to be ready..."
      - kubectl wait --for=condition=available --timeout=300s deployment/argocd-server -n argocd

  argocd:password:
    desc: Get ArgoCD admin password
    cmds:
      - |
        kubectl -n argocd get secret argocd-initial-admin-secret \
          -o jsonpath="{.data.password}" | base64 -d && echo

  argocd:port-forward:
    desc: Port forward ArgoCD UI to localhost:8080
    cmds:
      - kubectl port-forward svc/argocd-server -n argocd 8080:443

  # ============================================================================
  # Observability
  # ============================================================================
  grafana:port-forward:
    desc: Port forward Grafana to localhost:3000
    cmds:
      - kubectl port-forward svc/grafana -n monitoring 3000:80

  prometheus:port-forward:
    desc: Port forward Prometheus to localhost:9090
    cmds:
      - kubectl port-forward svc/prometheus-server -n monitoring 9090:80

  openclaw:port-forward:
    desc: Port forward OpenClaw to localhost:18789
    cmds:
      - kubectl port-forward svc/openclaw -n openclaw 18789:18789

  # ============================================================================
  # Kubernetes Utilities
  # ============================================================================
  k:pods:
    desc: List all pods
    cmds:
      - kubectl get pods -A

  k:nodes:
    desc: List all nodes
    cmds:
      - kubectl get nodes -o wide

  k:top:
    desc: Show resource usage
    cmds:
      - kubectl top nodes
      - kubectl top pods -A --sort-by=memory | head -20

  k:validate:
    desc: Validate cluster deployment
    cmds:
      - ./scripts/validate-cluster.sh

  # ============================================================================
  # Secrets
  # ============================================================================
  sops:encrypt:
    desc: Encrypt a secrets file with SOPS
    cmds:
      - sops -e {{.CLI_ARGS}} > {{.CLI_ARGS}}.enc.yaml

  sops:edit:
    desc: Edit an encrypted secrets file
    cmds:
      - sops {{.CLI_ARGS}}

  # ============================================================================
  # Maintenance
  # ============================================================================
  clean:
    desc: Clean build artifacts
    cmds:
      - pnpm clean
      - rm -rf node_modules/.cache

  prune:
    desc: Prune unused Docker resources
    cmds:
      - docker system prune -af
