# Loki Helm values for local K3d development
# Chart: grafana/loki

# Single binary mode - suitable for local dev
deploymentMode: SingleBinary

loki:
  auth_enabled: false

  commonConfig:
    replication_factor: 1

  storage:
    type: filesystem

  schemaConfig:
    configs:
      - from: 2024-01-01
        store: tsdb
        object_store: filesystem
        schema: v13
        index:
          prefix: index_
          period: 24h

  limits_config:
    retention_period: 24h  # Short retention for local dev


singleBinary:
  replicas: 1
  resources:
    requests:
      cpu: 50m
      memory: 128Mi
    limits:
      cpu: 200m
      memory: 256Mi
  persistence:
    enabled: false  # No persistence for local dev
  extraVolumes:
    - name: var-loki
      emptyDir: {}
  extraVolumeMounts:
    - name: var-loki
      mountPath: /var/loki

# Disable components not needed for single binary mode
backend:
  replicas: 0
read:
  replicas: 0
write:
  replicas: 0

gateway:
  enabled: false

# Disable caches - not needed for local dev and consume memory
chunksCache:
  enabled: false
resultsCache:
  enabled: false

# Disable monitoring
monitoring:
  selfMonitoring:
    enabled: false
    grafanaAgent:
      installOperator: false
  lokiCanary:
    enabled: false
