# OpenClaw Application
# Personal AI assistant with Groq and Telegram integration

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: openclaw
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/florisjonkman/raspberry-monorepo.git  # TODO: Replace florisjonkman
    targetRevision: main
    path: infrastructure/argocd/applications/openclaw
  destination:
    server: https://kubernetes.default.svc
    namespace: openclaw
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
