# Root Application - App of Apps pattern
# This application manages all other ArgoCD applications

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/<your-username>/raspberry-monorepo.git  # UPDATE THIS
    targetRevision: main
    path: infrastructure/argocd/applications
    directory:
      recurse: false
      exclude: 'root.yaml'
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
