# Grafana Helm values
# Chart: grafana/grafana
# https://github.com/grafana/helm-charts/tree/main/charts/grafana

replicas: 1

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 512Mi

persistence:
  enabled: true
  size: 1Gi
  storageClassName: local-path

adminUser: admin
# Password from shared secret
admin:
  existingSecret: shared-credentials
  userKey: admin-user
  passwordKey: admin-password

ingress:
  enabled: true
  ingressClassName: traefik
  hosts:
    - grafana.pi.local
  tls:
    - secretName: grafana-tls
      hosts:
        - grafana.pi.local

datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        url: http://prometheus-server.monitoring.svc.cluster.local
        access: proxy
        isDefault: true

      - name: Loki
        type: loki
        url: http://loki.monitoring.svc.cluster.local:3100
        access: proxy

dashboardProviders:
  dashboardproviders.yaml:
    apiVersion: 1
    providers:
      - name: 'default'
        orgId: 1
        folder: ''
        type: file
        disableDeletion: false
        editable: true
        options:
          path: /var/lib/grafana/dashboards/default

dashboards:
  default:
    # Kubernetes cluster monitoring
    kubernetes-cluster:
      gnetId: 315
      revision: 3
      datasource: Prometheus

    # Node exporter
    node-exporter:
      gnetId: 1860
      revision: 33
      datasource: Prometheus
