# Loki Helm values
# Chart: grafana/loki
# https://github.com/grafana/loki/tree/main/production/helm/loki
# Optimized for Raspberry Pi 4 (limited memory)

# Single binary mode - minimal footprint for single node
deploymentMode: SingleBinary

loki:
  auth_enabled: false

  commonConfig:
    replication_factor: 1
    path_prefix: /var/loki

  storage:
    type: filesystem

  schemaConfig:
    configs:
      - from: 2024-01-01
        store: tsdb
        object_store: filesystem
        schema: v13
        index:
          prefix: index_
          period: 24h

  # Disable ruler to avoid ruler-storage initialization
  rulerConfig:
    storage:
      type: local
      local:
        directory: /var/loki/rules

singleBinary:
  replicas: 1
  resources:
    requests:
      cpu: 50m
      memory: 128Mi
    limits:
      cpu: 300m
      memory: 256Mi
  persistence:
    enabled: true
    size: 2Gi
    storageClassName: local-path
  extraVolumeMounts:
    - name: data
      mountPath: /var/loki

# Disable ALL extra components for minimal memory usage
backend:
  replicas: 0
read:
  replicas: 0
write:
  replicas: 0

gateway:
  enabled: false

# Disable caches (too memory hungry for Pi)
chunksCache:
  enabled: false
resultsCache:
  enabled: false

# Disable monitoring components
monitoring:
  selfMonitoring:
    enabled: false
    grafanaAgent:
      installOperator: false
  lokiCanary:
    enabled: false

# Disable ruler completely
ruler:
  enabled: false
